import { writeFile } from "node:fs";
import { Buffer } from "node:buffer";

const data = new Uint8Array(
  Buffer.from("This file has been generated by the script.mjs file.")
);
writeFile("./exercise-10/message.txt", data, (err) => {
  if (err) throw err;
  console.log("The file has been saved!");
});
